version: '3'

services:
  teamtalk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttda
    restart: on-failure
    ports:
      - "10333:10333"
      - "10333:10333/udp"
    volumes:
      - /root/repo/comTT:/server/data
    networks:
      - teamtalk-net

networks:
  teamtalk-net:
    driver: bridge
