name: Create Pull Request

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update Repository
          title: 'Update Repository'
          body: 'This PR updates the repository with the latest changes.'
          branch: 'update-repository'

      - name: Copy repository contents via scp to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: "/root/repo/TeamTalk-5-em-docker"

      - name: Executing remote command on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
              cd ./repo/TeamTalk-5-em-docker/
              docker compose build
              docker compose down
              docker compose up -d
              docker compose logs